# Generated by Django 3.2.9 on 2021-11-14 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnimusIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Unimus_Address', models.URLField()),
                ('API_Token', models.TextField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 101', regex='^.{101}$')])),
                ('Verify_Certificate', models.BooleanField(default=False)),
                ('Test', models.BooleanField(default=True)),
            ],
        ),
    ]
