# Generated by Django 3.2.9 on 2022-01-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_unimus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unimusintegration',
            old_name='Test',
            new_name='Test_Unimus_Connection',
        ),
    ]
